name: 'algraphr'
version: 0.0.1
description: An absolute bare-bones web app.
author: rxlabz <erick@rxlabz.com>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  js: '^0.6.0'
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- dart_to_js_script_rewriter
